name: photo_editing_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-122.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Core Utility
  #UI
  #State Management
  #Authentication

  #Fonts and Icons
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  

  flutter_lints: ^2.0.0
  

flutter:
  fonts: 
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-BlackItalic.ttf
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-BoldItalic.ttf
        - asset: fonts/Lato-Italic.ttf
        - asset: fonts/Lato-Light.ttf
        - asset: fonts/Lato-LightItalic.ttf
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Thin.ttf
        - asset: fonts/Lato-ThinItalic.ttf
  uses-material-design: true
