name: photo_editing_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-122.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Core Utility
  flutter_screenutil: ^5.0.4
  image_downloader: ^0.31.0
  image_picker: ^0.8.5+3


  #UI
  flutter_staggered_grid_view: ^0.6.2
  lottie: ^1.4.2
  
  #Network
  http: ^0.13.5
  json_serializable: ^6.1.4
  json_annotation: ^4.6.0
  path_provider: ^2.0.11
  share_plus: ^4.1.0
  
  #State Management
  equatable: ^2.0.5
  provider: ^6.0.2
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0

  #Authentication

  #Fonts and Icons
  google_fonts: ^3.0.1
  fluentui_system_icons: ^1.1.153
  cupertino_icons: ^1.0.2

  #Code Generation
  build_runner: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  

  flutter_lints: ^2.0.0
  

flutter:
  assets:
    - assets/lottie/
  fonts: 
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-BlackItalic.ttf
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-BoldItalic.ttf
        - asset: fonts/Lato-Italic.ttf
        - asset: fonts/Lato-Light.ttf
        - asset: fonts/Lato-LightItalic.ttf
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Thin.ttf
        - asset: fonts/Lato-ThinItalic.ttf
  uses-material-design: true
